[package]
name = "rain"
edition = "2024.beta"
version = "0.1.0"

[dependencies]
deepbook = { local = "../../deepbookv3/packages/deepbook" }
token    = { local = "../../deepbookv3/packages/token", override = true }
# Pyth: add when implementing oracle_adapter. Example (may need correct subdir for your Sui CLI):
# Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }

[addresses]
rain = "0x0"
